name: Build

on:
  push:
    branches: [master]
    paths:
      - '**/*gradle*'
      - src/**/*.java
      - vscode-extension/src/**/*.ts
      - vscode-extension/src/*.js*
      - .github/workflows/*.yml
  pull_request:
    branches: [master]
    paths:
      - '**/*gradle*'
      - src/**/*.java
      - vscode-extension/src/**/*.ts
      - vscode-extension/src/*.js*
      - .github/workflows/*.yml

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        java-version: ["21", "25"]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v5
        with:
          distribution: "temurin"
          java-version: ${{ matrix.java-version }}

      - name: Build language server with Gradle
        run: |
          ./gradlew clean build
          ls build/libs/groovy-language-server-all.jar

      - name: Build VSCode extension with Gradle
        working-directory: vscode-extension
        run: |
          ./gradlew clean build
          ls build/groovyls-0.0.0.vsix

      - uses: actions/upload-artifact@v7
        if: ${{ matrix.java-version == '21' }}
        with:
          path: build/libs/groovy-language-server-all.jar
          archive: false
          if-no-files-found: error

      - uses: actions/upload-artifact@v7
        if: ${{ matrix.java-version == '21' }}
        with:
          path: vscode-extension/build/groovy-*.vsix
          archive: false
          if-no-files-found: error
